name: read file

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  read_file:
    name: read the contents of the file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: main

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: pwd
        run: pwd

      - name: read file
        run: cat main/src/hello.js

      - name: run hello.js
        run: node src/hello.js
